events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Handle Vue Router (SPA fallback)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy API calls to backend
        location /api/ {
           # proxy_pass http://backend:8080/;
            #proxy_set_header Host $host;
           # proxy_set_header X-Real-IP $remote_addr;
           
            proxy_pass https://backend.jollytree-f4b4af46.uksouth.azurecontainerapps.io/api/;
            proxy_set_header Host backend.jollytree-f4b4af46.uksouth.azurecontainerapps.io;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_server_name on;
           
        }

        # Security headers
        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
    }
}