// <auto-generated />
using System;
using IncidentReportingApplication.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentReportingApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncidentReportingApplication.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Low");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("New");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentNumber")
                        .IsUnique();

                    b.ToTable("Incidents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "user1@company.com",
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #1 involving a hardware failure that requires attention.",
                            DueDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0001",
                            IsEscalated = false,
                            Location = "Building 2, Floor 1",
                            Severity = "Low",
                            Status = "New",
                            Title = "Incident #1 - Data Breach"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "user2@company.com",
                            CreatedAt = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #2 involving a network issue that requires attention.",
                            DueDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0002",
                            IsEscalated = false,
                            Location = "Building 4, Floor 2",
                            Severity = "Medium",
                            Status = "Investigating",
                            Title = "Incident #2 - System Failure"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "user3@company.com",
                            CreatedAt = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #3 involving a hardware failure that requires attention.",
                            DueDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0003",
                            IsEscalated = true,
                            Location = "Building 1, Floor 3",
                            Severity = "High",
                            Status = "Resolved",
                            Title = "Incident #3 - Data Breach"
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "user4@company.com",
                            CreatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #4 involving a network issue that requires attention.",
                            DueDate = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0004",
                            IsEscalated = false,
                            Location = "Building 3, Floor 1",
                            Severity = "Critical",
                            Status = "New",
                            Title = "Incident #4 - System Failure"
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = "user5@company.com",
                            CreatedAt = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #5 involving a hardware failure that requires attention.",
                            DueDate = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0005",
                            IsEscalated = true,
                            Location = "Building 5, Floor 2",
                            ResolutionNotes = "Resolved by user5 after investigation.",
                            Severity = "Medium",
                            Status = "Resolved",
                            Title = "Incident #5 - Data Breach"
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = "user6@company.com",
                            CreatedAt = new DateTime(2025, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #6 involving a network issue that requires attention.",
                            DueDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0006",
                            IsEscalated = false,
                            Location = "Building 6, Floor 3",
                            Severity = "High",
                            Status = "Investigating",
                            Title = "Incident #6 - System Failure"
                        },
                        new
                        {
                            Id = 7,
                            AssignedTo = "user7@company.com",
                            CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #7 involving a hardware failure that requires attention.",
                            DueDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0007",
                            IsEscalated = false,
                            Location = "Building 7, Floor 4",
                            Severity = "Low",
                            Status = "Closed",
                            Title = "Incident #7 - Data Breach"
                        },
                        new
                        {
                            Id = 8,
                            AssignedTo = "user8@company.com",
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #8 involving a network issue that requires attention.",
                            DueDate = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0008",
                            IsEscalated = true,
                            Location = "Building 8, Floor 1",
                            Severity = "Critical",
                            Status = "New",
                            Title = "Incident #8 - System Failure"
                        },
                        new
                        {
                            Id = 9,
                            AssignedTo = "user9@company.com",
                            CreatedAt = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #9 involving a hardware failure that requires attention.",
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0009",
                            IsEscalated = false,
                            Location = "Building 9, Floor 3",
                            Severity = "High",
                            Status = "Investigating",
                            Title = "Incident #9 - Data Breach"
                        },
                        new
                        {
                            Id = 10,
                            AssignedTo = "user10@company.com",
                            CreatedAt = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a detailed description of incident #10 involving a network issue that requires attention.",
                            DueDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentNumber = "INC-2025-0010",
                            IsEscalated = false,
                            Location = "Building 10, Floor 2",
                            ResolutionNotes = "Resolved by user10 after investigation.",
                            Severity = "Medium",
                            Status = "Resolved",
                            Title = "Incident #10 - System Failure"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
